// NEED TO DRAW UP HTML
//NEED TO FIGURE OUT IF THE WIREFRAMES ARE REFLECTIVE OF THE ENTIRE USER JOURNEY
//DEEP DIVE NEEDED INTO THE API USE, CAN IT DO WHAT I NEED IT TO DO?
//WHAT DO I WANT THIS TO LOOK LIKE IN CSS
//WHAT IS A GOOD LOGIN / SIGN UP API I CAN USE, DO YOU EVEN NEED THAT AT THIS STAGE?
//WHAT IS THE BEST TYPEFORM API 